### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by maximmcnair** [ycinfinity/react-native-tvos-controller#2]
I get this error `Native module cannot be null` when running example and when adding to my own project. 

<img width="1436" alt="screen shot 2017-06-09 at 15 59 18" src="https://user-images.githubusercontent.com/1009787/26981305-a56e84c8-4d2c-11e7-9e9b-ad5f604a3f1f.png">

**Comment by navratill** [comment]
Did you linked native module into your tvOS target? Be aware that with 

`react-native link react-native-tvos-controller`

it just linking react-native-tvos-controller library to iOS target, but you will have to link it with tvOS target manually!
