### ISSUE TITLE
Redefinition of "RCTMethodInfo"

### ISSUE THREAD

**Issue by mxmtsk** [ycinfinity/react-native-tvos-controller#4]
Hi,
I'm having trouble building the app. Build fails with the following error:

`Redefinition of "RCTMethodInfo"

<img width="1249" alt="bildschirmfoto 2018-08-21 um 10 41 13" src="https://user-images.githubusercontent.com/4848184/44390974-e989c900-a52e-11e8-9c63-7590e1fc1423.png">

**Comment by mxmtsk** [comment]
Have to test it a little bit more but replacing

```
#import "RCTBridgeModule.h"
```

with

```
#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#else
#import "RCTBridgeModule.h"
#endif
```

in `RCTNativeTvosController.h` fixed it for me and should work for newer and older React Native Versions.

**Comment by respectTheCode** [comment]
I had to make the same change mxmtsk suggested.
